###################################################################

# Created by write_sdc on Wed Jan 19 18:42:47 2022

###################################################################
set sdc_version 2.1

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[31]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[30]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[29]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[28]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[27]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[26]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[25]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[24]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[23]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[22]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[21]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[20]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[19]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[18]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[17]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[16]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[15]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[14]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[13]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[12]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[11]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[10]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[9]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[8]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[7]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[6]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[5]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[4]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[3]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[2]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[1]}]
set_load -pin_load 3.40189 [get_ports {address_instruction_mem[0]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[31]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[30]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[29]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[28]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[27]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[26]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[25]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[24]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[23]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[22]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[21]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[20]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[19]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[18]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[17]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[16]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[15]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[14]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[13]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[12]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[11]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[10]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[9]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[8]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[7]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[6]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[5]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[4]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[3]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[2]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[1]}]
set_load -pin_load 3.40189 [get_ports {write_data_mem[0]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[31]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[30]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[29]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[28]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[27]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[26]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[25]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[24]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[23]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[22]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[21]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[20]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[19]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[18]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[17]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[16]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[15]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[14]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[13]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[12]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[11]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[10]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[9]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[8]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[7]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[6]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[5]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[4]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[3]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[2]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[1]}]
set_load -pin_load 3.40189 [get_ports {address_data_mem[0]}]
set_load -pin_load 3.40189 [get_ports read_enable_data_memory]
set_load -pin_load 3.40189 [get_ports write_enable_data_memory]
create_clock [get_ports clk]  -name MY_CLK  -period 10  -waveform {0 5}
set_clock_uncertainty 0.07  [get_clocks MY_CLK]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports clk]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports rst_n]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {instruction[0]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[31]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[30]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[29]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[28]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[27]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[26]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[25]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[24]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[23]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[22]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[21]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[20]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[19]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[18]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[17]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[16]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[15]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[14]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[13]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[12]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[11]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[10]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[9]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[8]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[7]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[6]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[5]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[4]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[3]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[2]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[1]}]
set_input_delay -clock MY_CLK  -max 0.5  [get_ports {read_data_mem[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_instruction_mem[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {write_data_mem[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[31]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[30]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[29]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[28]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[27]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[26]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[25]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[24]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[23]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[22]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[21]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[20]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[19]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[18]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[17]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[16]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[15]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[14]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[13]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[12]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[11]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[10]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[9]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[8]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[7]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[6]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[5]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[4]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[3]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[2]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[1]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports {address_data_mem[0]}]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports read_enable_data_memory]
set_output_delay -clock MY_CLK  -max 0.5  [get_ports write_enable_data_memory]
